"""initial

Revision ID: dddaac545046
Revises: 
Create Date: 2026-06-10 04:53:45.821588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddaac545046'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corsi',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('data_inizio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fine', sa.DateTime(timezone=True), nullable=True),
    sa.Column('orario', sa.String(length=100), nullable=True),
    sa.Column('durata', sa.String(length=100), nullable=True),
    sa.Column('luogo', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('posti_totali', sa.Integer(), nullable=True),
    sa.Column('posti_occupati', sa.Integer(), nullable=True),
    sa.Column('timeout_pagamento_ore', sa.Integer(), nullable=True),
    sa.Column('coordinate_bancarie', sa.Text(), nullable=True),
    sa.Column('immagine_url', sa.String(length=500), nullable=True),
    sa.Column('pubblicato', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('attestato_template_url', sa.String(length=500), nullable=True),
    sa.Column('attestato_nome_file', sa.String(length=255), nullable=True),
    sa.Column('attestato_html_template', sa.Text(), nullable=True),
    sa.Column('attestato_abilitato', sa.Boolean(), nullable=True),
    sa.Column('ultima_notifica_marketing', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_notifica_leads', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impostazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chiave', sa.String(length=100), nullable=False),
    sa.Column('valore', sa.Text(), nullable=True),
    sa.Column('gruppo', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impostazioni', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impostazioni_chiave'), ['chiave'], unique=True)

    op.create_table('leads_marketing',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cognome', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('verificato', sa.Boolean(), nullable=True),
    sa.Column('token_verifica', sa.String(length=255), nullable=True),
    sa.Column('token_scadenza', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_contatto', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads_marketing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_marketing_email'), ['email'], unique=True)

    op.create_table('utenti',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('ruolo', sa.Enum('UTENTE', 'SEGRETERIA', 'ADMIN', name='ruolo'), nullable=False),
    sa.Column('email_verificata', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_reset', sa.String(length=255), nullable=True),
    sa.Column('scadenza_token', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consenso_privacy', sa.Boolean(), nullable=True),
    sa.Column('consenso_marketing', sa.Boolean(), nullable=True),
    sa.Column('data_consenso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utenti_email'), ['email'], unique=True)

    op.create_table('prenotazioni',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utente_id', sa.String(), nullable=False),
    sa.Column('corso_id', sa.String(), nullable=False),
    sa.Column('numero_posti', sa.Integer(), nullable=True),
    sa.Column('stato', sa.Enum('IN_ATTESA_PAGAMENTO', 'PAGAMENTO_CARICATO', 'CONFERMATA', 'ANNULLATA', 'SCADUTA', name='statoprenotazione'), nullable=True),
    sa.Column('scadenza_pagamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metodo_pagamento', sa.Enum('BONIFICO', 'STRIPE', 'PAYPAL', name='metodopagamento'), nullable=True),
    sa.Column('id_transazione', sa.String(length=255), nullable=True),
    sa.Column('importo_pagato', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('url_contabile', sa.String(length=500), nullable=True),
    sa.Column('nome_file_contabile', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('note_segreteria', sa.Text(), nullable=True),
    sa.Column('attestato_url', sa.String(length=500), nullable=True),
    sa.Column('attestato_emesso', sa.Boolean(), nullable=True),
    sa.Column('attestato_emesso_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['corso_id'], ['corsi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partecipanti',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prenotazione_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['prenotazione_id'], ['prenotazioni.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partecipanti')
    op.drop_table('prenotazioni')
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utenti_email'))

    op.drop_table('utenti')
    with op.batch_alter_table('leads_marketing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_marketing_email'))

    op.drop_table('leads_marketing')
    with op.batch_alter_table('impostazioni', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impostazioni_chiave'))

    op.drop_table('impostazioni')
    op.drop_table('corsi')
    # ### end Alembic commands ###
